# Generated by Django 4.0.5 on 2022-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_post',
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_coment',
            field=models.DateTimeField(),
        ),
    ]
